### ISSUE TITLE
HTML Renderer supported?

### ISSUE THREAD

**Issue by FloLech** [fivethree-team/lottie#20]
Is the html renderer supported? When I set the renderer option to "html" there is no output on my screen. SVG and Canvas work like a charm.

**Comment by marcjulian** [comment]
It should be supported by lottie-web and it works in the example project. However, it is not displayed when the component is inside a flex layout and I haven't found a solution so far.

**Comment by marcjulian** [comment]
@FloLech do you get it working in your project?
